

/*
const promise = new Promise((resolve, reject) => {
  //resolve([1, 2, 3]);
  //reject("There was an error!");
});


console.log(promise);

promise
  .then(value => console.log(value))
  .catch(error => console.log(error))
  .finally(() => console.log("Heyy!"));


console.log("Hello!");
*/



/*
const value = 2;

const promise = new Promise((resolve, reject) => {
  const random = Math.floor(Math.random() * 3);
  if (random === value) {
    resolve("You guessed correctly!")
  } else {
    reject("Wrong number!")
  }
});


console.log(promise);

promise
  .then(value => console.log(value))
  .catch(error => console.log(error));
*/



